### ISSUE TITLE
missing uart.flush() on official micropython

### ISSUE THREAD

**Issue by kevinkk525** [kevinkk525/pms5003_micropython#1]
The driver was written for loboris port of esp32 and official micropython doesn't have uart.flush() implemented.
As soon as [https://github.com/micropython/micropython/pull/5156](https://github.com/micropython/micropython/pull/5156) is merged, I'll update the driver to use the flush() method.

**Comment by 2114L3** [comment]
perhaps the readme needs clarification as its currently suggests specially for micropython which is very confusing reading your comment here.

is there a work around in the meantime?

**Comment by kevinkk525** [comment]
> suggests specially for micropython

That's because it is for micropython specifically? The loboris fork is micropython too.
Sadly I am not aware of any workaround and my last ping in the micropython PR didn't receive any answers.
I will update the project and docs as soon as there's some progress.

However you could probably implement the changes of that PR into your micropython firmware and then it should work. (might need renaming uart.flush)
