### ISSUE TITLE
Running example results in errors

### ISSUE THREAD

**Issue by mraess** [kevinkk525/pms5003_micropython#4]
Hi @kevinkk525 I'm running the `pms5003_test.py` example on an ESP32 with MicroPython 1.14 and while the code seems to run, I'm getting `Got no available bytes` and no data returns from the PMS5003.

Here is what the output looks like

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5008
ho 0 tail 12 room 4
load:0x40078000,len:10600
ho 0 tail 12 room 4
load:0x40080400,len:5684
entry 0x400806bc

wakeUp
wakeUp got lock
Sending command: 228,1,False,16000
waiting 40.0s
Got no available bytes
Sending command: 228,1,False,16000
waiting 40.0s
Got no available bytes
No response to wakeup command
wakeUp
wakeUp got lock
Sending command: 228,1,False,16000
waiting 40.0s


----------------------------------------------------------

Setting to active mode while sleeping

----------------------------------------------------------


Got no available bytes
Sending command: 228,1,False,16000
waiting 40.0s
Got no available bytes
No response to wakeup command
wakeUp
wakeUp got lock
Sending command: 228,1,False,16000
waiting 40.0s


----------------------------------------------------------

Setting to passive mode whithout sleeping with 20s interval

----------------------------------------------------------


Got no available bytes
Sending command: 228,1,False,16000
waiting 40.0s
Got no available bytes
No response to wakeup command
Resetting not responding device
No reset pin defined, can't reset
Shutting device down as it is not responding


----------------------------------------------------------

Activating EcoMode, interval will be adapted to 60s

----------------------------------------------------------
```

And also this `TypeError`

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5008
ho 0 tail 12 room 4
load:0x40078000,len:10600
ho 0 tail 12 room 4
load:0x40080400,len:5684
entry 0x400806bc
wakeUp
wakeUp got lock
Sending command: 228,1,False,16000
waiting 40.0s
readFrame False False
__read_frame
readFrame got: (39, 62, 66, 29, 47, 57, 7005, 1991, 370, 19, 5, 2, 38656, 1089)
Got (39, 62, 66, 29, 47, 57, 7005, 1991, 370, 19, 5, 2, 38656, 1089)
device woke up
setPassiveMode
setPassiveMode got lock
Sending command: 225,0,True,1000
readFrame False False
__read_frame
Received command response frame: [66, 77, 0, 4, 225, 0, 1, 116]
readFrame got: True
Got True
setPassiveMode done
wakeUp done
_read got lock
Sending command: 226,0,False,10000
readFrame False False
__read_frame
got no values
Task exception wasn't retrieved
future: <Task> coro= <Task>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "pms5003.py", line 355, in _read
  File "pms5003.py", line 254, in _sendCommand
  File "pms5003.py", line 417, in _read_frame
  File "pms5003.py", line 456, in __read_frame
TypeError: object of type 'NoneType' has no len()
```

UART is connected on `TX = Pin 25` and `RX = Pin 26` as in your example. What am I doing wrong? Is there a simple way to test whether the PMS5003 actually works, i.e. is not a dud?

I've also made a post in the MicroPython Forum: https://forum.micropython.org/viewtopic.php?f=14&t=4934&p=56267#p56267

Any insights are really appreciated!

**Comment by kevinkk525** [comment]
can you read the uart directly without the driver? like does "uart.read()" return anything?

**Comment by mraess** [comment]
So with this

```
uart = machine.UART(1, baudrate = 9600, tx = 25, rx = 26)
uart.init(bits = 8, parity = None, stop = 1)
```

or this

```
uart = machine.UART(1, tx=25, rx=26, baudrate=9600)
```

`uart.write('test')` returns `4` and `uart.read()` returns nothing.

Then, I realized I'm an idiot because I had connected RX.sensor = RX.ESP32 and vice versa for TX instead of RX.sensor = TX.ESP32 and vice versa for RX.

Now `uart.read()` returns this

```
>>> uart.read()
b'BM\x00\x1c\x00&\x00:\x00?\x00\x1d\x00-\x008\x19#\x07D\x01I\x00*\x00\x06\x00\x02\x97\x00\x03fBM\x00\x1c\x00%\x00:\x00@\x00\x1d\x00-\x008\x18\xd2\x07\x1f\x01O\x00.\x00\x07\x00\x03\x97\x00\x03\xfbBM\x00\x1c\x00%\x00:\x00@\x00\x1d\x00-\x008\x18\xd2\x07\x1f\x01O\x00.\x00\x07\x00\x03\x97\x00\x03\xfbBM\x00\x1c\x00%\x00:\x00@\x00\x1d\x00-\x008\x18\xd2\x07\x1f\x01O\x00.\x00\x07\x00\x03\x97\x00\x03\xfb'
```

However, when I run the example, I still get this error

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5008
ho 0 tail 12 room 4
load:0x40078000,len:10600
ho 0 tail 12 room 4
load:0x40080400,len:5684
entry 0x400806bc
wakeUp
wakeUp got lock
Sending command: 228,1,False,16000
waiting 40.0s
readFrame False False
__read_frame
readFrame got: (36, 52, 55, 28, 42, 51, 6060, 1783, 329, 13, 4, 3, 38656, 1128)
Got (36, 52, 55, 28, 42, 51, 6060, 1783, 329, 13, 4, 3, 38656, 1128)
device woke up
setPassiveMode
setPassiveMode got lock
Sending command: 225,0,True,1000
readFrame False False
__read_frame
Received command response frame: [66, 77, 0, 4, 225, 0, 1, 116]
readFrame got: True
Got True
setPassiveMode done
wakeUp done
_read got lock
Sending command: 226,0,False,10000
readFrame False False
__read_frame
got no values
Task exception wasn't retrieved
future: <Task> coro= <Task>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "pms5003.py", line 355, in _read
  File "pms5003.py", line 254, in _sendCommand
  File "pms5003.py", line 417, in _read_frame
  File "pms5003.py", line 456, in __read_frame
TypeError: object of type 'NoneType' has no len()
```

Weirdly enough, when I run the simplified example from the ReadMe

```
import pms5003
import machine
import uasyncio as asyncio

uart = machine.UART(1, tx=25, rx=26, baudrate=9600)
pm = pms5003.PMS5003(uart)
pm.registerCallback(pm.print)

loop=asyncio.get_event_loop()
loop.run_forever()
```

I do get output now

```
---------------------------------------------
Measurement 1ms ago at 2000-01-01 00:01:09
---------------------------------------------
Concentration Units (standard)
---------------------------------------------
PM 1.0: 32	PM2.5: 53	PM10: 56
Concentration Units (environmental)
---------------------------------------------
PM 1.0: 26	PM2.5: 42	PM10: 51
---------------------------------------------
Particles > 0.3um / 0.1L air: 5646
Particles > 0.5um / 0.1L air: 1662
Particles > 1.0um / 0.1L air: 332
Particles > 2.5um / 0.1L air: 35
Particles > 5.0um / 0.1L air: 3
Particles > 10 um / 0.1L air: 2
---------------------------------------------
```

So I wonder where the disconnect to the more complex test example in the `pms5003_test.py` file is.

**Comment by kevinkk525** [comment]
Seems like your sensor doesn't like the passive mode or needs longer to wake up than expected. The simple example uses the active mode so just reacts to whenever the sensor sends a new measurement.

**Comment by mraess** [comment]
@kevinkk525 I think you're right. I set `active_mode=True` and now it's working! Any idea if this means it's a faulty sensor? Are there any disadvantages of using the sensor in active mode exclusively?

**Comment by kevinkk525** [comment]
I don't know if the sensor is faulty or just a cheap clone that doesn't support all features (are there even cheap clones? I bought mine from aliexpress and it works fine..).
There are no disadvantages to using it in active mode exclusively. You just have to make sure your callback/coroutine can process the data quick enough so it doesn't stack. If the active mode produces too many measurements, you can just discard some in your callback or create an average or something like that.
The passive and eco modes are especially interesting if you run a battery powered setup as it allows to put the sensor to sleep. If that's not your use-case, active mode will be just fine.

**Comment by mraess** [comment]
Okay, good to know. Yeah, I bought mine from Adafruit, so no cheap know off. I'll experiment around a little bit. I assume I can just set everything up as co-routines? I'm thinking I'm `awaiting` the sensor wake up in another `async` function that then either sends the data via `mqtt` or maybe even `blynk`

Anyways, thanks for the quick replies and help here. I think we can close this issue out.

**Comment by kevinkk525** [comment]
Adafruit, interesting. So maybe it's not completely the same sensor but with some debugging you might be able to find the difference and make it work. Of course that only makes sense if the passive mode has any benefits to your application.

awaiting sensor.wakeUp() is the wrong approach, that methods should probably not be called by an application. You could register an asyncio Event and then just "casually" await that event and send a mqtt message in an interval of your choosing. Alternatively run a separate coroutine with a chosen interval and just read the sensor values. Since the sensor values provide a timestamp attribute of the last read, you can easily check if the sensor works (data not older than your last iteration).

**Comment by mraess** [comment]
Ah gotcha. Yes, that makes sense! I'll just read the sensor in a coroutine or try the event route.

Thanks!

**Comment by kevinkk525** [comment]
Glad we could solve your problem.
If you have further questions, feel free to write on the forum again or open an issue.
